package com.github.dkwasniak.screenshotcompare.settings

import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.util.xmlb.XmlSerializerUtil

/**
 * Project-level persisted configuration. The screenshot directories are project specific, so the
 * user picks them per project (on first run, or later in Settings).
 */
@Service(Service.Level.PROJECT)
@State(
    name = "ScreenshotCompareSettings",
    storages = [Storage("screenshotCompare.xml")]
)
class ScreenshotSettings : PersistentStateComponent<ScreenshotSettings.State> {

    class State {
        // Absolute paths to directories that contain screenshot golden files.
        var paths: MutableList<String> = ArrayList()
        // Absolute paths to directories that contain screenshots generated by verification tests.
        var generatedPaths: MutableList<String> = ArrayList()
        // Regex for selecting generated screenshots. First capture group maps to the golden basename.
        var generatedFileRegex: String = DEFAULT_GENERATED_FILE_REGEX
    }

    private var state = State()

    override fun getState(): State = state

    override fun loadState(loaded: State) {
        XmlSerializerUtil.copyBean(loaded, state)
    }

    var paths: List<String>
        get() = state.paths.toList()
        set(value) {
            state.paths = value.toMutableList()
        }

    var generatedPaths: List<String>
        get() = state.generatedPaths.toList()
        set(value) {
            state.generatedPaths = value.toMutableList()
        }

    var generatedFileRegex: String
        get() = state.generatedFileRegex.ifBlank { DEFAULT_GENERATED_FILE_REGEX }
        set(value) {
            state.generatedFileRegex = value.ifBlank { DEFAULT_GENERATED_FILE_REGEX }
        }

    val isConfigured: Boolean
        get() = state.paths.isNotEmpty()

    val hasGeneratedPaths: Boolean
        get() = state.generatedPaths.isNotEmpty()

    companion object {
        const val DEFAULT_GENERATED_FILE_REGEX = "^(.+)_actual\\.png$"

        fun getInstance(project: Project): ScreenshotSettings = project.service()
    }
}
