package com.github.dkwasniak.goldendiff.compare

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class FigmaImageSourceTest {

    // Runtime registration goes through the `com.github.dkwasniak.goldendiff.comparisonSource`
    // extension point (see plugin.xml); that path needs a running platform, so here we only assert the
    // source's identity and that its first-run defaults resource is packaged with the plugin.
    @Test
    fun `figma source exposes its identity and bundled first-run defaults`() {
        val source = FigmaImageSource()
        assertEquals("figma", source.id)
        val defaults = source.firstRunDefaults()
        assertTrue("defaults resource should be on the classpath", defaults != null)
        assertTrue(defaults!!.goldenPaths.isNotEmpty())
        assertTrue(defaults.generatedPaths.isNotEmpty())
    }

    @Test
    fun `parses figma generated preview block before annotations`() {
        val previews = FigmaImageSource().parseFigmaPreviews(
            """
            // Generated by figma-compose-preview — do not edit; used for Roborazzi–Figma pixel comparison.
            // Figma source: https://www.figma.com/design/fileKey/File?node-id=1-2&m=dev
            @Preview(uiMode = Configuration.UI_MODE_NIGHT_YES, locale = "en", showSystemUi = false)
            @Composable
            fun PlanRouteScreenFigmaSelectedRouteDarkPreview() {
                PreviewSurface(ignorePadding = true) {
                }
            }
            """.trimIndent(),
        )

        assertEquals(
            listOf(
                FigmaPreview(
                    "PlanRouteScreenFigmaSelectedRouteDarkPreview",
                    "https://www.figma.com/design/fileKey/File?node-id=1-2&m=dev",
                ),
            ),
            previews,
        )
    }
}
