package com.github.dkwasniak.goldendiff.settings

import com.github.dkwasniak.goldendiff.match.MatchMode
import com.github.dkwasniak.goldendiff.match.MatchingDefaults
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.util.xmlb.XmlSerializerUtil

/**
 * Project-level persisted configuration. The screenshot directories are project specific, so the
 * user picks them per project (on first run, or later in Settings).
 */
@Service(Service.Level.PROJECT)
@State(
    name = "GoldenDiffSettings",
    storages = [Storage("goldenDiff.xml")]
)
class ScreenshotSettings : PersistentStateComponent<ScreenshotSettings.State> {

    class State {
        // Absolute paths to directories that contain screenshot golden files.
        var paths: MutableList<String> = ArrayList()
        // Absolute paths to directories that contain screenshots generated by verification tests.
        var generatedPaths: MutableList<String> = ArrayList()
        // Regex for selecting generated screenshots. First capture group maps to the golden basename.
        var generatedFileRegex: String = DEFAULT_GENERATED_FILE_REGEX
        // Which matching mode is active. See MatchMode.
        var matchMode: String = MatchingDefaults.DEFAULT_MATCH_MODE.name
        // Regex applied to annotation names. Matching annotated functions become golden candidates.
        var annotatedFunctionRegex: String = MatchingDefaults.ANNOTATION_NAME_REGEX
        // Regex patterns for the file/class matching mode. Support {file_name} and {class_name}.
        var goldenFilePatterns: MutableList<String> = MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS.toMutableList()
        // File-name suffixes (before the extension) whose files are not goldens themselves and are
        // excluded from the golden list, e.g. Roborazzi's `_compare` / `_actual` artifacts.
        var excludedSuffixes: MutableList<String> = DEFAULT_EXCLUDED_SUFFIXES.toMutableList()
    }

    private var state = State()

    override fun getState(): State = state

    override fun loadState(loaded: State) {
        XmlSerializerUtil.copyBean(loaded, state)
    }

    var paths: List<String>
        get() = state.paths.toList()
        set(value) {
            state.paths = value.toMutableList()
        }

    var generatedPaths: List<String>
        get() = state.generatedPaths.toList()
        set(value) {
            state.generatedPaths = value.toMutableList()
        }

    var generatedFileRegex: String
        get() = state.generatedFileRegex.ifBlank { DEFAULT_GENERATED_FILE_REGEX }
        set(value) {
            state.generatedFileRegex = value.ifBlank { DEFAULT_GENERATED_FILE_REGEX }
        }

    var excludedSuffixes: List<String>
        get() = state.excludedSuffixes.toList()
        set(value) {
            state.excludedSuffixes = value.toMutableList()
        }

    var matchMode: MatchMode
        get() = MatchMode.fromName(state.matchMode)
        set(value) {
            state.matchMode = value.name
        }

    var annotatedFunctionRegex: String
        get() = state.annotatedFunctionRegex.ifBlank { MatchingDefaults.ANNOTATION_NAME_REGEX }
        set(value) {
            state.annotatedFunctionRegex = value.ifBlank { MatchingDefaults.ANNOTATION_NAME_REGEX }
        }

    var goldenFilePatterns: List<String>
        get() = state.goldenFilePatterns.ifEmpty { MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS }.toList()
        set(value) {
            state.goldenFilePatterns = value.ifEmpty { MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS }.toMutableList()
        }

    val isConfigured: Boolean
        get() = state.paths.isNotEmpty()

    val hasGeneratedPaths: Boolean
        get() = state.generatedPaths.isNotEmpty()

    companion object {
        const val DEFAULT_GENERATED_FILE_REGEX = "^(.+)_actual\\.png$"
        val DEFAULT_EXCLUDED_SUFFIXES = listOf("_compare", "_actual")

        fun getInstance(project: Project): ScreenshotSettings = project.service()
    }
}
